# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WaterNetworkTools
                                 A QGIS plugin
 Water Network Modelling Utilities
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-07-22
        copyright            : (C) 2019 by Andrés García Martínez
        email                : ppnoptimizer@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Andrés García Martínez'
__date__ = '2019-07-22'
__copyright__ = '(C) 2019 by Andrés García Martínez'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WaterNetworkTools class from file WaterNetworkTools.

    :param iface: A QGIS interface instance
    :type iface: QgsInterface
    """
    #
    from .wnt import WaterNetworkToolsPlugin
    return WaterNetworkToolsPlugin()
